'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.Kickstart

    Partial Public Class Settings

        '''<summary>
        '''lblViewMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblViewMode As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpViewMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpViewMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rowListTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowListTab As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblListTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblListTab As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpListTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpListTab As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rowDetailsTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rowDetailsTab As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblDetailsTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetailsTab As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpDetailsTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpDetailsTab As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblModuleTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblModuleTheme As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpModuleTheme control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpModuleTheme As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
