'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.Kickstart

    Partial Public Class frmFund

        '''<summary>
        '''lblFundingHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingHeader As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFundingIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWarning As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblValidate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblValidate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlIncentiveSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlIncentiveSelect As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSelectIncentive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectIncentive As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpFundingAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpFundingAmount As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlIncentiveDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlIncentiveDescription As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSelectedIncentive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectedIncentive As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblFundingIncentive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingIncentive As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFundingAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingAmount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlFundingAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlFundingAmount As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''lblCurrency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrency As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblAnonymousFunding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAnonymousFunding As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAnonymous control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAnonymous As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdAddFunding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddFunding As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDeleteFunding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteFunding As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
