'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.Kickstart

    Partial Public Class frmProject

        '''<summary>
        '''pnlWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWarning As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWarning As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblHeading As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblManagersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManagersNeeded As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlManagersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlManagersNeeded As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''lblDevelopersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDevelopersNeeded As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlDevelopersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDevelopersNeeded As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''lblDesignersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDesignersNeeded As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlDesignersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDesignersNeeded As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''lblTranslatorsNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTranslatorsNeeded As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlTranslatorsNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTranslatorsNeeded As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''lblTestersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTestersNeeded As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlTestersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTestersNeeded As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''lblFundingIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''drpFundingCurrency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpFundingCurrency As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ctlFundingNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlFundingNeeded As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''pnlIncentives control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlIncentives As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblIncentives control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIncentives As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblIncentiveIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIncentiveIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFundingAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingAmount As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlFundingAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlFundingAmount As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''lblIncentive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIncentive As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtIncentive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIncentive As Global.DotNetNuke.Web.UI.WebControls.DnnTextBox

        '''<summary>
        '''rptIncentives control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptIncentives As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''cmdAddIncentive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddIncentive As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSummary As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSummary As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDescription As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContent As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDateScheduled As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDateScheduled As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''lblProjectPlatform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectPlatform As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpProjectPlatform control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpProjectPlatform As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblPlatformRSSUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPlatformRSSUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPlatformRSSUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPlatformRSSUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPlatformUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPlatformUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPlatformUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPlatformUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblLogoUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLogoUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtLogoUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLogoUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblIsDelivered control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIsDelivered As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkIsDelivered control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsDelivered As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDateDelivered control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDateDelivered As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlDateDelivered control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDateDelivered As Global.DotNetNuke.Web.UI.WebControls.DnnDatePicker

        '''<summary>
        '''lblCurrentVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentVersion As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCurrentVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCurrentVersion As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDownloadUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDownloadUrl As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDownloadUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDownloadUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rptTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptTeam As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlLocked control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLocked As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblLockedNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLockedNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlDeleted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDeleted As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDeletedNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDeletedNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdUpdateConfig control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdateConfig As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdRestore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRestore As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdLock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLock As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUnlock control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUnlock As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
