'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.Kickstart

    Partial Public Class frmParticipate

        '''<summary>
        '''lblParticipateHeading control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblParticipateHeading As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblParticipateIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblParticipateIntro As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlManagers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlManagers As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblManagersHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManagersHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblManagersDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManagersDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblManagersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManagersCurrent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlManagersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlManagersCurrent As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblManagersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManagersNeeded As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdBecomeManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBecomeManager As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdStopManaging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStopManaging As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlDevelopers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDevelopers As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDevelopersHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDevelopersHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblDevelopersDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDevelopersDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblDevelopersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDevelopersCurrent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlDevelopersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDevelopersCurrent As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDevelopersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDevelopersNeeded As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdBecomeDeveloper control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBecomeDeveloper As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdStopDeveloping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStopDeveloping As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlDesigners control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDesigners As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDesignersHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDesignersHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblDesignersDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDesignersDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblDesignersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDesignersCurrent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlDesignersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDesignersCurrent As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblDesignersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDesignersNeeded As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdBecomeDesigner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBecomeDesigner As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdStopDesigning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStopDesigning As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlTranslators control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTranslators As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTranslatorsHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTranslatorsHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTranslatorsDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTranslatorsDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTranslatorsCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTranslatorsCurrent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlTranslatotsCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTranslatotsCurrent As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTranlatorsNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTranlatorsNeeded As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdBecomeTranslator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBecomeTranslator As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdStopTranslating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStopTranslating As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlTesters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTesters As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTestersHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTestersHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTestersDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTestersDescription As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTestersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTestersCurrent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlTestersCurrent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTestersCurrent As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTestersNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTestersNeeded As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdBecomeTester control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBecomeTester As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdStopTesting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStopTesting As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
