'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.Kickstart

    Partial Public Class Funding

        '''<summary>
        '''lblFundingHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFundingNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingNeeded As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFundingReached control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingReached As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblMeterSpan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMeterSpan As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lnkFund control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkFund As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
