'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.Kickstart

    Partial Public Class ProjectSidebar

        '''<summary>
        '''pnlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlStatus As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''imgStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgStatus As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlFunding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFunding As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblFundingHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFundingNeeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingNeeded As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblFundingReached control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFundingReached As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblMeterSpan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMeterSpan As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lnkFund control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkFund As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''pnlParticipation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlParticipation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlMembers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMembers As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblOwnerHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOwnerHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''imgLead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLead As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblLeadName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLeadName As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lnkLeadProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkLeadProfile As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''pnlTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTeam As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTeam As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptTeam As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlNoLead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNoLead As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblNoLead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoLead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlParticipate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlParticipate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkParticipate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkParticipate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''pnlRelease control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRelease As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblReleasesHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReleasesHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblCurrentReleaseVersionLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentReleaseVersionLabel As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblCurrentReleaseVersion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentReleaseVersion As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblCurrentReleaseDateLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentReleaseDateLabel As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblCurrentReleaseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentReleaseDate As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lnkDownload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkDownload As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
