'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Connect.Modules.Kickstart

    Partial Public Class ProjectMembers

        '''<summary>
        '''lblOwnerHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOwnerHead As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''imgLead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgLead As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblLeadName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLeadName As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lnkLeadProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkLeadProfile As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTeam As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''rptTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptTeam As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlParticipate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlParticipate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkParticipate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkParticipate As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
